trigger: none
pool: Default

parameters:
- name: envorment
  type: string
  default: dev
  values:
  - dev
  - qa
  - prod

variables:
- name: workingDir
  value: envorment/${{ parameters.envorment }}

- ${{ if eq(parameters.envorment, 'dev') }}:
  - group: infra-test-july-terraform-dev

- ${{ if eq(parameters.envorment, 'qa') }}:
  - group: infra-test-july-terraform-qa

- ${{ if eq(parameters.envorment, 'prod') }}:
  - group: infra-test-july-terraform-prod
 

stages:
  - stage:
    displayName: Package install 
    jobs:
      - job: 
        displayName: Agent packege install
        steps:
        - script: sudo apt install unzip -y
        - script: sudo apt install openjdk-17-jdk -y
        - script: sudo apt install python3-pip -y

  - stage:
    displayName: terraform 
    jobs:
      - job: 
        displayName: terraform init plan
        steps:
        - task: TerraformInstaller@1
          displayName: terraform install
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workingdir)'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'july-service'
            backendAzureRmResourceGroupName: '$(resourcegroupname)'
            backendAzureRmStorageAccountName: '$(storageaccountname)'
            backendAzureRmContainerName: '$(containername)'
            backendAzureRmKey: '$(key)'

        # - task: TerraformTask@5
        #   displayName: terraform plan
        #   inputs:
        #     provider: 'azurerm'
        #     command: 'plan'
        #     workingDirectory: '$(workingdir)'
        #     environmentServiceNameAzureRM: 'july-service'


  - stage:
    displayName: scaning 
    jobs:
      - job: 
        displayName: scaning tools
        steps:
        - task: CmdLine@2
          displayName: Install Gitleaks
          inputs:
            script: |
              VERSION=v8.30.1
              sudo wget https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz
              sudo tar -xzf gitleaks_${VERSION}_linux_x64.tar.gz
              sudo mv gitleaks /usr/local/bin/
              sudo gitleaks version

        # - task: CmdLine@2
        #   displayName: checkov install
        #   inputs:
        #     script: |
        #       sudo python3 -m pip install --upgrade pip
        #       sudo pip3 install checkov
        #       sudo checkov --version
        # - task: CmdLine@2
        #   displayName: checkov scane
        #   continueOnError: true
        #   inputs:
        #     script: 'sudo checkov -d . --framework terraform'
        # - task: tfsec@1
        #   displayName: tfsec
        #   inputs:
        #     version: 'v1.26.0'
        #     dir: '$(workingdir)'

        # - task: dependency-check-build-task@6
        #   displayName: waspzap scan
        #   inputs:
        #     projectName: 'owaspzap'
        #     scanPath: '$(workingdir)'
        #     format: 'HTML'
        #     uploadReports: true

  # - stage: 
  #   displayName: ManualApproval

  #   jobs:
  #   - job: ManualValidation
  #     displayName: "Manual Gate"

  #     pool: server

  #     steps:
  #     - task: ManualValidation@1
  #       timeoutInMinutes: 1440

  #       inputs:
  #         notifyUsers: |
  #           raushankr28@gmail.com

  #         approvers: |
  #           Raushan

  #         instructions: |
  #           Please review the deployment and approve to continue.

  #         onTimeout: reject
  # - stage: 
  #   displayName: terraformapply
  #   jobs:
  #   - job: 
  #     displayName: terraform apply
  #     steps:
  #         - task: TerraformTask@5
  #           inputs:
  #             provider: 'azurerm'
  #             command: 'init'
  #             workingDirectory: '$(workingdir)'
  #             backendAzureRmUseEntraIdForAuthentication: false
  #             backendServiceArm: 'july-service'
  #             backendAzureRmResourceGroupName: '$(resourcegroupname)'
  #             backendAzureRmStorageAccountName: '$(storageaccountname)'
  #             backendAzureRmContainerName: '$(containername)'
  #             backendAzureRmKey: '$(key)'
  #         - task: TerraformTask@5
  #           inputs:
  #             provider: 'azurerm'
  #             command: 'apply'
  #             workingDirectory: '$(workingdir)'
  #             environmentServiceNameAzureRM: 'july-service'